package dedi.controller;

import dedi.database.DatabaseConnection;
import dedi.model.Prototipe;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

/**
 * Controller for managing prototype history data in the DeDi application.
 * Uses native JDBC to interact directly with the {@code prototipe} table
 * in the PostgreSQL database.
 *
 * <p>This class handles CRUD operations for prototypes, including retrieving
 * the version history based on an innovation idea, adding new versions,
 * and updating the progress status of a specific prototype version.
 */
public class PrototipeController {

    /**
     * Retrieves the entire prototype version history for a specific innovation idea.
     * Data is fetched and ordered in ascending order (ASC) based on {@code id_prototipe}.
     *
     * @param idIde The ID of the innovation idea whose prototype history is to be retrieved.
     * @return A {@link List} containing {@link Prototipe} objects associated with the idea.
     * Returns an empty list if no data is found or if a connection error occurs.
     */
    public List<Prototipe> getRiwayatPrototipe(int idIde){
        List<Prototipe> daftarRiwayat = new ArrayList<>();

        try{
            Connection connection = DatabaseConnection.getInstance();

            String query = "SELECT * FROM prototipe WHERE id_ide = ? ORDER BY id_prototipe ASC";
            PreparedStatement preparedStatement = connection.prepareStatement(query);

            preparedStatement.setInt(1, idIde);
            ResultSet result = preparedStatement.executeQuery();

            while (result.next()){
                Prototipe prototipe = new Prototipe();

                prototipe.setIdPrototipe(result.getInt("id_prototipe"));
                prototipe.setIdIde(result.getInt("id_ide"));
                prototipe.setVersi(result.getString("versi"));
                prototipe.setStatus(result.getString("status"));
                prototipe.setDeskripsiPerubahan(result.getString("deskripsi_perubahan"));

                daftarRiwayat.add(prototipe);
            }
        } catch (SQLException e){
            e.printStackTrace();
        }

        return daftarRiwayat;
    }

    /**
     * Saves a new prototype version record into the database.
     * The {@code id_prototipe} attribute will be auto-generated by the database (SERIAL type).
     *
     * @param prototipeBaru The {@link Prototipe} object containing the details of the new version.
     * @return {@code true} if the data is successfully saved to the database, {@code false} otherwise.
     */
    public boolean manageVersi(Prototipe prototipeBaru) {
        String query = "INSERT INTO prototipe (id_ide, versi, status, deskripsi_perubahan) VALUES (?, ?, ?, ?)";

        try {
            Connection connection = DatabaseConnection.getInstance();
            PreparedStatement preparedStatement = connection.prepareStatement(query);

            preparedStatement.setInt(1, prototipeBaru.getIdIde());
            preparedStatement.setString(2, prototipeBaru.getVersi());
            preparedStatement.setString(3, prototipeBaru.getStatus());
            preparedStatement.setString(4, prototipeBaru.getDeskripsiPerubahan());


            int barisBerubah = preparedStatement.executeUpdate();

            if (barisBerubah > 0) {
                return true;
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }

        return false;
    }

    /**
     * Updates the development progress status of an existing prototype version.
     *
     * @param idPrototipe The unique ID of the prototype whose status is to be updated.
     * @param statusBaru  The new status text (e.g., "Done" or "OnGoing").
     * @return {@code true} if the status is successfully updated in the database, {@code false} otherwise.
     */
    public boolean updateProgress(int idPrototipe, String statusBaru) {
        String query = "UPDATE prototipe SET status = ? WHERE id_prototipe = ?";

        try {
            Connection connection = DatabaseConnection.getInstance();
            PreparedStatement preparedStatement = connection.prepareStatement(query);

            preparedStatement.setString(1, statusBaru);
            preparedStatement.setInt(2, idPrototipe);

            int barisBerubah = preparedStatement.executeUpdate();

            if (barisBerubah > 0) {
                return true;
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }

        return false;
    }
}